### ISSUE TITLE
Hata alıyorum

### ISSUE THREAD

**Issue by tamertoprakk** [aykanugur/Earthquake-Database-For-Turkey#1]
Hocam merhaba, exe'yi çalıştırınca bu şekilde hata alıyorum. Yardımcı olabilir misiniz acaba?
![resim_2024-07-23_185859315](https://github.com/user-attachments/assets/e7968986-8a1f-46af-aefd-24204fff09bb)

**Comment by aykanugur** [comment]
Hemen yardımcı olayım hata kullandığım resimleri exe içine koymamış olduğumdan kaynaklanıyor hemen düzeltiyim Bildirdiğiniz için çok teşekkürler

**Comment by aykanugur** [comment]
İlk Pyhton projem olduğundan tecrübesizlikten kaynaklanan bir hata :)

**Comment by aykanugur** [comment]
Bugün içinde düzeltirim

**Comment by aykanugur** [comment]
Bilgilendirme için yazıyorum bilgisayarımda bir sorun oluştu o yüzden bugün yapabilir miyim bilmiyorum

**Comment by aykanugur** [comment]
Bilgilendirme için yazıyorum sorun çözüldü 2 pc ile test ettim exe dosyasını kaynakların yanından ayırmadığınız sürece problem olmaz

**Comment by tamertoprakk** [comment]
![image](https://github.com/user-attachments/assets/0798a6b4-04d1-4b3e-9b12-f623efd13f1f)

**Comment by tamertoprakk** [comment]
ayırmadım aslında, yine aynı hatayı veriyor ne yazık ki exe'yi çalıştırdığım zaman

**Comment by tamertoprakk** [comment]
loginkey.json'la ilgili bi problem var sanırım

**Comment by aykanugur** [comment]
![Ekran görüntüsü 2024-07-25 153607](https://github.com/user-attachments/assets/45b4ac9d-b8d8-4fe4-ad00-61ab54919258)

Programda 6.satırda hata olduğu yazıyor ama 6.satırda kod yok. 6 tane bilgisayar ile test ettim hiç böyle bir hata ile karşılaşmadım.
Programın en son sürümünü kullandığınıza emin misiniz ? Eski sürümlerde loginkey.json kullanmıştım ama bu hataya sebebiyet verdiğinden bu dosyanın içindeki key bilgilerini programın içine gömdüm. Lütfen programın en son sürümünü kullandığınıza emin olun.

**Comment by aykanugur** [comment]
Lütfen son.rar içindeki exe yi kullanın

**Comment by tamertoprakk** [comment]
sorun aynı şekilde devam ediyor. Rica etsem rar'ı birde buradan yorum olarak yükler misiniz? Belki de yaptığınız güncellemeler ana linki modifiye etmiyordur.

**Comment by aykanugur** [comment]
Buradan dosya atamıyorum, ama sizin için tekrar güncelledim program indirme kısmını 
![1](https://github.com/user-attachments/assets/35ee057e-5427-48fa-9813-38a877b97115)
![2](https://github.com/user-attachments/assets/ee3650db-742a-45fe-bbfe-51c570aa2d16)

Resimde gösterdiğim gösterdiğim yerden indirirseniz bir problem olmaz. Son.rar içindeki exe yi kullanacaksınız.
Tam şimdi bir arkadaşıma test ettirdim. Bir problem yaşamadı.

**Comment by tamertoprakk** [comment]
Tamamdır hocam düzelmiş şimdi. Teşekkürler. Olumlu eleştiri babında kabul ederseniz eğer, kayıt olup giriş yapıldıktan sonra profil'e tekrar basınca geriye gitme seçeneği yok, sadece güncelle butonu çıkıyor ve daha önce girdiğim profil bilgileri boş geliyor, kodlarda orada eskiklik var bilginiz olsun. Ayrıca tam ekran olmuyor ne yazık ki. Rasathane verilerinin bir tık üstüne koymak için ise harita üzerinde şehir bazında deprem büyüklüğü/tarihi parametresini infografik bir harita görünümüyle görsel olaraktan verileri programda sunabilirseniz eğer farklı bi hava katmış olursunuz diye düşünüyorum naçizane. Başarılar ve kolaylıklar dilerim size.
